services:
  - type: web
    runtime: docker
    name: fastapi-backend
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: "/health/"  # Ensure this endpoint exists in your FastAPI app
    dockerfilePath: "ollama-deployment/app/backend/Dockerfile"
    networks:
      - tutorial-net

  - type: web
    name: streamlit-frontend
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BACKEND_URL
        value: "http://fastapi-backend:8000"  # Connects Streamlit to FastAPI internally
    healthCheckPath: "/health"  # Ensure this endpoint exists in your Streamlit app
    dockerfilePath: "ollama-deployment/app/frontend/Dockerfile"
    networks:
      - tutorial-net
    
  - type: background
    name: ollama
    runtime: docker
    buildCommand: "docker build -t ollama-image ollama"
    startCommand: "docker run -p 11434:11434 ollama-image"
    volumes:
      - tutorial-vol:/ollama
    networks:
      - tutorial-net
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]

networks:
  tutorial-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local
